### ISSUE TITLE
Import gene set

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#197]
Click on the 'Import gene set'  to open the "Copy/Paste" box. The box runs outside of the panel and the 'Done' button is also outside the panel.

**Comment by tonydisera** [comment]
Can you send me a screenshot?  I tried it on all 3 browsers and couldn't reproduce.  I did, however, find a bug on FireFox and Safari.  When you click on Import Genes and the dropdown opens, if you click inside the textarea, the dropdown closes.   I have fixed this bug.

**Comment by AlistairNWard** [comment]
<img width="252" alt="screen shot 2016-02-03 at 10 44 00 am" src="https://cloud.githubusercontent.com/assets/523111/12787931/6d4328ec-ca65-11e5-82c4-c644fab9f28e.png">

On Chrome

**Comment by AlistairNWard** [comment]
Note that I am working directly on my laptop, not on a large external screen.

**Comment by AlistairNWard** [comment]
Just hooked up an external monitor to check and I still see the same behaviour. There is a horizontal scroll bar so I can scroll across, but it seems like this should be sized to the size of the box.

**Comment by tonydisera** [comment]
I see.  Good catch.  I'll see if I can reproduce by changing my monitor resolution.

**Comment by tonydisera** [comment]
When I lowered my laptop's resolution, I did see problems where the tooltip row for allele freq was rendering outside of tooltip.  I also saw a problem with the positioning of the phenotype tooltip under the gene button where the tooltip width exceeded the outer edge of the browser window.  I fixed both of these bugs, but I can't reproduce the 'Import Genes' problem you have found.  Let's try to look at this on Monday.

**Comment by AlistairNWard** [comment]
I just tried this again on my laptop and it still happens. We can try and reproduce next week while I'm in SLC, but import bookmarks etc is still wider than the left panel.

**Comment by AlistairNWard** [comment]
I just tried again on my big screen and I see this. I also noticed that the 'Run' button in genes overruns the disclaimer.

**Comment by AlistairNWard** [comment]
I keep trying to reproduce, but haven't seen this for a while. I'm going to push it to the next milestone and if I don't see it again, I'll close it.

**Comment by AlistairNWard** [comment]
Still haven't seen this again, although I keep trying. Maybe it got fixed somewhere along the way. I'm going to close this, but we should keep it in mind in case it comes up again.
